orbs:
  architect: giantswarm/architect@dev:go-mod-tidy-1-17

version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: renovate-playground
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
